server:
  port: ${PORT:8000}
spring:
  application:
    name: user-api
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:user-api
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console.enabled: true
